### ISSUE TITLE
Consider rename to reflect extension purpose

### ISSUE THREAD

**Issue by xurizaemon** [eileenmcnaughton/org.wikimedia.contacteditor#1]
CiviCRM already has "contact editing" in core & ["contact edit" / "editing contacts"](https://docs.civicrm.org/user/en/latest/organising-your-data/contacts/#editing-contacts) is an established term.

If this extension is named to reflect more accurately what it does ("change contact type"?), people who need to use it should have a better chance of finding it.

If this extension is going to become a replacement contact editor screen, then "contacteditor" makes more sense to me.

My suggestion would be `changecontacttype` - most of the Google results for "CiviCRM change contact type" are this request, so this would put your extension where those people are already looking.

**Comment by eileenmcnaughton** [comment]
Hmm I think I went for the generic name because I felt like implicit in the decision to put this in an extension rather than core (which has also been questioned) was the fact I would probably add other stuff to it in time.....

**Comment by xurizaemon** [comment]
Fair enough :grin:

**Comment by petednz** [comment]
ha - look at us FZ (ex) folk all over here - i had exact same thought - and will now butt out since the answer explains your thinking.
