### ISSUE TITLE
changin type, no success

### ISSUE THREAD

**Issue by petrodin** [eileenmcnaughton/org.wikimedia.contacteditor#10]
Hi, trying to change invidual to organization..
i get error "please provide a custom value for addresee greeting"
![kuva](https://user-images.githubusercontent.com/47251707/152633603-b61fb94a-f5fe-45a4-b20f-091f3603dd5a.png)
![kuva](https://user-images.githubusercontent.com/47251707/152633631-6c35b7b7-da76-4c1f-8bed-8e06ebfd3eae.png)
But i think i have provided custom values for those that requested..

**Comment by eileenmcnaughton** [comment]
I'm gonna close this out cos it got too old & I don't think you are gonna want to help debug it now...
