### ISSUE TITLE
When installing this I get an error for the polyfill

### ISSUE THREAD

**Issue by ErikHommel** [eileenmcnaughton/org.wikimedia.contacteditor#13]
Installing locally as a test for Amnesty International Vlaanderen on CiviCRM 5.37.2 I get this error:

`Fatal error: require(): Failed opening required '/var/www/html/aivldev/sites/default/files/civicrm/ext/org.wikimedia.contacteditor-2.3/mixin/polyfill.php' (include_path='/var/www/html/aivldev/sites/default/files/civicrm/ext/org.wikimedia.contacteditor-2.3/:/var/www/html/aivldev/sites/default/files/civicrm/ext/streetrecruitmentimport/:/var/www/html/aivldev/sites/default/files/civicrm/ext/finsburypark/:/var/www/html/aivldev/sites/default/files/civicrm/ext/dataprocessor/:/var/www/html/aivldev/sites/default/files/civicrm/ext/koalecttocivi/:/var/www/html/aivldev/sites/default/files/civicrm/ext/de.systopia.moregreetings/:/var/www/html/aivldev/sites/all/modules/civicrm/ext/afform/admin/:/var/www/html/aivldev/sites/all/modules/civicrm/ext/afform/html/:/var/www/html/aivldev/sites/all/modules/civicrm/ext/afform/core/:/var/www/html/aivldev/sites/default/files/civicrm/ext/com.cividesk.apikey/:/var/www/html/aivldev/sites/default/files/civicrm/ext/aivlcsvimports/:/var/www/html/aivldev/sites/default/files/civicrm/ext/org.civicrm.recentm in /var/www/html/aivldev/sites/default/files/civicrm/ext/org.wikimedia.contacteditor-2.3/contacteditor.civix.php on line 85`

**Comment by ErikHommel** [comment]
When doing a 
`civix mixin --enable-all` as recommended in this issue: https://github.com/totten/civix/issues/244 I do not get any pages or forms as the menus are not updated. When adding the workaround xmlMenu function as suggested in the issue it does show the form and I can complete the edit process.

**Comment by eileenmcnaughton** [comment]
which release are you using? THe compatibility for the master branch is set to 5.53 & hence master does nto ship the mixin

https://github.com/eileenmcnaughton/org.wikimedia.contacteditor/blob/master/info.xml#L21

**Comment by eileenmcnaughton** [comment]
Closing - works on supported versions
