### ISSUE TITLE
Undefined method retrieveValue()

### ISSUE THREAD

**Issue by gljk** [eileenmcnaughton/org.wikimedia.contacteditor#2]
I get the following error when I go to change type action:

`Fatal error: Call to undefined method CRM_Utils_Request::retrieveValue() in D:\xampp\htdocs\sites\default\files\civicrm\ext\org.wikimedia.contacteditor-1.0\CRM\Contacteditor\Form\ContactTypeChange.php on line 35`

This is the latest Civicrm 4.7.29

**Comment by eileenmcnaughton** [comment]
Oh yeah - I think that method might not be in the live version yet - it should be in 4.7.30

**Comment by gljk** [comment]
Ah... That makes perfect sense.

**Comment by aburns348** [comment]
When attempting to change contact type it pushes me to a 404 error on the front end.  Also using 4.7.29. 

The URL looks like this:

https://myurl.org/civicrm/contacttypechange?contact_id=26135&cid=26135
