### ISSUE TITLE
Pushed to 404 error page

### ISSUE THREAD

**Issue by andyburnsco** [eileenmcnaughton/org.wikimedia.contacteditor#3]
When attempting to change contact type it pushes me to a 404 error on the front end. Also using 4.7.29.

The URL looks like this:

https://myurl.org/civicrm/contacttypechange?contact_id=26135&cid=26135

I'll try and get a specific error...

**Comment by eileenmcnaughton** [comment]
it does need 4.7.30....

**Comment by andyburnsco** [comment]
Ah, I am changing from Org type to a subtype which is no issue without the extension. 

It appears I don't need this utility at this moment but we did upgrade to 4.7.30 on a mulitisite and the actions button shortcut that did not work.

**Comment by eileenmcnaughton** [comment]
hmm - I'm not quite sure why that is an issue :-(

**Comment by eileenmcnaughton** [comment]
Hmm - this is pretty old - I *htink* it's resolved
