### ISSUE TITLE
Organization names not created

### ISSUE THREAD

**Issue by tanyabouman** [eileenmcnaughton/org.wikimedia.contacteditor#4]
If I understand correctly, after changing the type of an individual to an organization, the full name of an individual should become the organization name.

However, this is not happening for me.  Instead, the individual's name only goes in the addressee field, and the organization name field is left blank.  I am using Backdrop 1.10.1, CiviCRM 5.2.2 and Contact Editor 2.0.

![typechange](https://user-images.githubusercontent.com/15057442/42651277-f20466e2-85dc-11e8-8c9b-58ebb4ac20e1.png)

In this example change, I created a test individual that only had a first and last name.  After changing the type from individual to organization, the only field that indicates the name of the organization is the addressee field.  The organization name is left empty, which makes it difficult to search for that contact.

**Comment by eileenmcnaughton** [comment]
I just did a test to confirm and the name IS saved to the organization_name field for me. Your result is a bit mysterious TBH since the organization_name was know at the point where the addressee was generated - but not saved!?!?!

Are there any other extensions and / or custom code that could be in play?

**Comment by tanyabouman** [comment]
Thanks for the info.  I disabled all the other extensions, but that didn't help.  I can't think of any custom code.  

It looks like the call `civicrm_api3('Contact', 'getsingle', ['id' => $contactID,'return' => $contactTypeSpecificFields,]);` in CRM/Contacteditor/ChangeContactType.php is not returning the first, middle and last names when it should.  It does get the nick name and legal name, though.  Mysterious, for sure.  I'll re-open the issue if it is related to Contact Editor.

**Comment by tanyabouman** [comment]
I found the problem.  It is in https://github.com/eileenmcnaughton/org.wikimedia.contacteditor/blob/master/CRM/Contacteditor/ChangeContactType.php in the definition of $contactTypeSpecificFields (line 44).

Since I have a number of custom fields, the union of $contactTypeSpecificCustomFields with the rest of the fields (birth_date, contact_sub_type, etc.) has duplicate keys and some of the fields get dropped.  I replaced the [+](http://php.net/manual/en/language.operators.array.php) with [array_merge](http://php.net/manual/en/function.array-merge.php), and it solved the problem for me.  Is this a good solution?

**Comment by eileenmcnaughton** [comment]
@tanyabouman if that works for you then that seems like the right fix - if you are able to put that as a PR I will merge it
