### ISSUE TITLE
Can't see Change Contact Type in the menu

### ISSUE THREAD

**Issue by khorporative** [eileenmcnaughton/org.wikimedia.contacteditor#7]
Hey!

I installed Contact Editor both on 5.13.5 and 5.17.3, however, I see no Change Contact Type in the Actions menu (_screenshot_) for a given contact. Why is that and how can I fix it?

![image](https://user-images.githubusercontent.com/18428628/64702177-bbb55080-d4b2-11e9-9276-1939b9b36215.png)

**Comment by eileenmcnaughton** [comment]
Check the notes in the readme
